Parameters:
  Tag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number
    Default: 0

  Cluster:
    Type: String

  Repository:
    Type: String
  
  LETSENCRYPTEMAIL:
    Type: String
    
  LETSENCRYPTHOST:
    Type: String
    
  CONTAINERPORT:
    Type: Number
  
  FACEBOOKCLIENTSECRET:
    Type: String
  
  FACEBOOKCLIENTID:
    Type: String
    
  FACEBOOKCALLBACKURL:
    Type: String
    
  FACEBOOKAPI:
    Type: String
  
  GOOGLECLIENTSECRET:
    Type: String
  
  GOOGLECLIENTID:
    Type: String
  
  GOOGLECALLBACKURL:
    Type: String
  
  GOOGLEBROWSERKEY:
    Type: String
  
  GOOGLESERVERKEY:
    Type: String
  
  GAPROPERTY:
    Type: String
  
  GADOMAIN:
    Type: String
  
  TWITTERCONSUMERKEY:
    Type: String
  
  TWITTERCONSUMERSECRET:
    Type: String
  
  TWITTERCALLBACKURL:
    Type: String
  
  CLOUDINARYURL:
    Type: String
  
  MAILGUNAPIKEY:
    Type: String
    
  MAILGUNDOMAIN:
    Type: String
 
  COOKIESECRET:
    Type: String
    


Resources:
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-service-${AWS::StackName}
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole
  
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      DeploymentConfiguration:
        MaximumPercent: 150
        MinimumHealthyPercent: 0
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition   

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-node-app
      ContainerDefinitions:
        - Name: node-app
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          EntryPoint:
            - npm
            - start
          Essential: true
          MemoryReservation: 128
          Links:
            - mongodb:mongodb
          PortMappings:
            - ContainerPort: !Ref CONTAINERPORT
          Environment:
            - Name: Tag
              Value: !Ref Tag
            - Name: NODE_ENV
              Value: 'production'
            - Name: PORT
              Value: !Ref CONTAINERPORT
            - Name: MONGO_URI
              Value: !Sub mongodb://mongodb/${Repository}
            - Name: FACEBOOK_CLIENT_SECRET
              Value: !Ref FACEBOOKCLIENTSECRET
            - Name: GOOGLE_CALLBACK_URL
              Value: !Ref GOOGLECALLBACKURL
            - Name: CLOUDINARY_URL
              Value: !Ref CLOUDINARYURL
            - Name: MAILGUN_API_KEY
              Value: !Ref MAILGUNAPIKEY
            - Name: MAILGUN_DOMAIN
              Value: !Ref MAILGUNDOMAIN
            - Name: GOOGLE_CLIENT_ID
              Value: !Ref GOOGLECLIENTID
            - Name: FACEBOOK_CLIENT_ID
              Value: !Ref FACEBOOKCLIENTID
            - Name: FACEBOOK_CALLBACK_URL
              Value: !Ref FACEBOOKCALLBACKURL
            - Name: GOOGLE_CLIENT_SECRET
              Value: !Ref GOOGLECLIENTSECRET
            - Name: FACEBOOK_API
              Value: !Ref FACEBOOKAPI
            - Name: COOKIE_SECRET
              Value: !Ref COOKIESECRET
            - Name: LETSENCRYPT_EMAIL
              Value: !Ref LETSENCRYPTEMAIL
            - Name: LETSENCRYPT_HOST
              Value: !Ref LETSENCRYPTHOST
            - Name: VIRTUAL_PORT
              Value: !Ref CONTAINERPORT
            - Name: VIRTUAL_HOST
              Value: !Ref LETSENCRYPTHOST
            - Name: GOOGLE_BROWSER_KEY
              Value: !Ref GOOGLEBROWSERKEY
            - Name: GOOGLE_SERVER_KEY
              Value: !Ref GOOGLESERVERKEY
            - Name: GA_PROPERTY
              Value: !Ref GAPROPERTY
            - Name: GA_DOMAIN
              Value: !Ref GADOMAIN
            - Name: TWITTER_CONSUMER_KEY
              Value: !Ref TWITTERCONSUMERKEY
            - Name: TWITTER_CALLBACK_URL
              Value: !Ref TWITTERCALLBACKURL
            - Name: TWITTER_CONSUMER_SECRET
              Value: !Ref TWITTERCONSUMERSECRET
        - Name: mongodb
          Image: mongo:3.4
          Essential: true
          MemoryReservation: 128
          MountPoints:
            - SourceVolume: !Sub ${AWS::StackName}-MongoDB-Vol
              ContainerPath: /data/db
      Volumes:
        - Name: !Sub ${AWS::StackName}-MongoDB-Vol
          Host:
            SourcePath: /opt/docker/benggdata
